% -------------------------------------------------------------------
% Generated by MATLAB on 23-Feb-2026 20:29:42
% MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
% このスクリプトの生成中、ルート Inport マッパーでは接続のない入力が無視されます。
simOut = runSimulation(); 

function simOut = runSimulation() 
% Create a cell array storing the file names of the input data 
cellOfFiles = { ...
'testPatternSimple3.xlsx.mat' , ...
'testPatternSimple3.xlsx.mat' , ...
'testPatternSimple3.xlsx.mat' , ...
'testPatternSimple3.xlsx.mat' , ...
}; 

% Create a cell array storing the file reader names for reading the input files 
cellOfFileReaderNames = { ...
'Simulink.io.MatFile' , ...
'Simulink.io.MatFile' , ...
'Simulink.io.MatFile' , ...
'Simulink.io.MatFile' , ...
}; 

% Create a cell array storing the variables names of the scenario data 
cellOfVarNames = { ...
'TC1' , ...
'TC2' , ...
'TC3' , ...
'TC4' , ...
}; 

% Create a cell array storing the input strings for each scenario 
cellOfInputStrings = { ...
'TC1.getElement(''gu8i1'')' , ...
'TC2.getElement(''gu8i1'')' , ...
'TC3.getElement(''gu8i1'')' , ...
'TC4.getElement(''gu8i1'')' , ...
}; 

cellOfErrors = cell(1,length( cellOfInputStrings ));
simOut = Simulink.SimulationOutput.empty(0,length( cellOfInputStrings ));
simIn  = Simulink.SimulationInput.empty(0,length( cellOfInputStrings ));

% For each scenario 
for kScenario = 1: length( cellOfInputStrings ) 
	 try 
	 	% Load Variable from file 
	 	loadScenarioToWorkspace( cellOfFiles{kScenario},cellOfVarNames{kScenario},[],cellOfFileReaderNames{kScenario}); 
	 	% set up SimulationInput object 
	 	simIn(kScenario) = Simulink.SimulationInput('test');
	 	simIn(kScenario).ExternalInput = cellOfInputStrings{kScenario};
	 	simIn(kScenario) = simIn(kScenario).setVariable( cellOfVarNames{kScenario}, evalin('base',(cellOfVarNames{kScenario})) );

ds = evalin('base', cellOfVarNames{kScenario});        
endTime = 0;
for i = 1:ds.numElements

    elem = ds{i};

    if isa(elem, 'timeseries')
        tEnd = elem.Time(end);
    else
        tEnd = elem.Values.Time(end);
    end

    endTime = max(endTime, tEnd);

end
simIn(kScenario) = simIn(kScenario).setModelParameter( ...
    'StopTime', num2str(endTime) );

	 	evalin('base',sprintf('clear %s',cellOfVarNames{kScenario}));
	 catch ME 
	 	cellOfErrors{ length(cellOfErrors) + 1 } = ME.message; 
	 end 
end 
% End for each scenario 

if ~isempty( simIn )
	simOut = parsim(simIn);
end 
% Report Errors 
idxEmpty = cellfun(@isempty, cellOfErrors); 
cellOfErrors(idxEmpty)= []; 
if ~isempty(cellOfErrors) 

	disp('このスクリプトの実行中にこれらのエラーが発生しました。');
	% For each error 
	for kErr = 1: length( cellOfErrors ) 
		disp(cellOfErrors{kErr}); 
	end 
	% End for each error 

end 
end 
