% -------------------------------------------------------------------
% Generated by MATLAB on 16-Apr-2026 15:53:20
% MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
% このスクリプトの生成中、ルート Inport マッパーでは接続のない入力が無視されます。
simOut = runSimulation(); 

function simOut = runSimulation() 
clc;
warning off;
% Create a cell array storing the file names of the input data 
cellOfFiles = { ...
'testPatternSimple4.xlsx' , ...
'testPatternSimple4.xlsx' , ...
'testPatternSimple4.xlsx' , ...
'testPatternSimple4.xlsx' , ...
'testPatternSimple4.xlsx' , ...
}; 

% Create a cell array storing the file reader names for reading the input files 
cellOfFileReaderNames = { ...
'Simulink.io.SignalBuilderSpreadsheet' , ...
'Simulink.io.SignalBuilderSpreadsheet' , ...
'Simulink.io.SignalBuilderSpreadsheet' , ...
'Simulink.io.SignalBuilderSpreadsheet' , ...
'Simulink.io.SignalBuilderSpreadsheet' , ...
}; 

% Create a cell array storing the variables names of the scenario data 
cellOfVarNames = { ...
'TC5' , ...
'TC4' , ...
'TC1' , ...
'TC2' , ...
'TC3' , ...
}; 

% Create a cell array storing the input strings for each scenario 
cellOfInputStrings = { ...
'TC5.getElement(''gu8i1'')' , ...
'TC4.getElement(''gu8i1'')' , ...
'TC1.getElement(''gu8i1'')' , ...
'TC2.getElement(''gu8i1'')' , ...
'TC3.getElement(''gu8i1'')' , ...
}; 

% Create configuration structure to cast spreadsheet data. 
spreadsheetDataTypeConfig(1).DataType = {'double','uint8'};
spreadsheetDataTypeConfig(1).Signals = {...
{2,3,4,5,6},...
{1}
};
spreadsheetDataTypeConfig(2).DataType = {'double','uint8'};
spreadsheetDataTypeConfig(2).Signals = {...
{2,3,4,5,6},...
{1}
};
spreadsheetDataTypeConfig(3).DataType = {'double','uint8'};
spreadsheetDataTypeConfig(3).Signals = {...
{2,3,4,5,6},...
{1}
};
spreadsheetDataTypeConfig(4).DataType = {'double','uint8'};
spreadsheetDataTypeConfig(4).Signals = {...
{2,3,4,5,6},...
{1}
};
spreadsheetDataTypeConfig(5).DataType = {'double','uint8'};
spreadsheetDataTypeConfig(5).Signals = {...
{2,3,4,5,6},...
{1}
};

cellOfErrors = cell(1,length( cellOfInputStrings ));
simOut = Simulink.SimulationOutput.empty(0,length( cellOfInputStrings ));
simIn  = Simulink.SimulationInput.empty(0,length( cellOfInputStrings ));

% For each scenario 
for kScenario = 1: length( cellOfInputStrings ) 
	 try 
	 	% Load Variable from file 
	 	loadScenarioToWorkspace( cellOfFiles{kScenario},cellOfVarNames{kScenario},spreadsheetDataTypeConfig(kScenario),cellOfFileReaderNames{kScenario}); 
	 	% set up SimulationInput object
	 	simIn(kScenario) = Simulink.SimulationInput('test');
        data = evalin('base',sprintf('%s.getElement(''gu8i1'')',cellOfVarNames{kScenario}));% add
        data.Data = uint8(data.Data);% add
        simIn(kScenario).ExternalInput = data;
        % simIn(kScenario).ExternalInput = cellOfInputStrings{kScenario};%del
	 	simIn(kScenario) = simIn(kScenario).setVariable( cellOfVarNames{kScenario}, evalin('base',(cellOfVarNames{kScenario})) );
        simTime = evalin('base',sprintf('%s.getElement(''gu8i1'').Time(end)',cellOfVarNames{kScenario}));% add
        simIn(kScenario) = simIn(kScenario).setModelParameter('StopTime', num2str(simTime));% add
	 	evalin('base',sprintf('clear %s',cellOfVarNames{kScenario}));
	 catch ME 
	 	cellOfErrors{ length(cellOfErrors) + 1 } = ME.message; 
	 end 
end 
% End for each scenario 

if ~isempty( simIn )
	simOut = parsim(simIn);
end 
% Report Errors 
idxEmpty = cellfun(@isempty, cellOfErrors); 
cellOfErrors(idxEmpty)= []; 
if ~isempty(cellOfErrors) 

	disp('このスクリプトの実行中にこれらのエラーが発生しました。');
	% For each error 
	for kErr = 1: length( cellOfErrors ) 
		disp(cellOfErrors{kErr}); 
	end 
	% End for each error 

end
save('simOut.mat','simOut'); % add
end